version: '1'
services:
  frontend:
    #build: ./frontend
    image: php:7.2-apache
    ports:
      - "81:80"
    volumes:  
      - ./frontend:/var/www/html


  backend:
    build: ./backend
    ports:
      - "82:80"
    volumes:
      - ./backend:/var/www/html

  db:
    image: mysql
    ports:
      - "3307:3306"
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf
    environment:
     MYSQL_DATABASE: mydb
     MYSQL_ROOT_PASSWORD: root
     MYSQL_AUTH_PLUGIN: mysql_native_password






